# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

extends: default

rules:
  anchors:
    forbid-undeclared-aliases: true
    forbid-unused-anchors: true
  braces:
    forbid: non-empty
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: non-empty
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  document-start: disable
  empty-lines:
    max: 1
  empty-values: enable
  float-values:
    forbid-inf: true
    forbid-nan: true
    forbid-scientific-notation: true
    require-numeral-before-decimal: true
  indentation:
    check-multi-line-strings: true
  line-length:
    max: 100
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: only-when-needed
